[package]
name = "pdfdownload"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
percent-encoding = "2.3.1"
reqwest = "0.11.27"
select = "0.5"
tokio = { version = "1", features = ["full"] }
